id: P000484
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20311
  title: ཕྱུགས་ལས་ཀྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    a407c1dabcee40f98ef6c870b62be0b0:
      image_group_id: I8LS20313
      title: Volume 1 of phyugs las kyi rgyun shes klog deb/
      volume_number: 1
      total_pages: 237
      base_file: v001.txt
